lbforum/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from lbforum import views, accountviews

forum_patterns = patterns(
    '',
    url(r'^(?P<forum_slug>\w+)/$', views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/$',
        views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/(?P<topic_type2>\w+)/$',
        views.forum, name='lbforum_forum'),
)

topic_patterns = patterns(
    '',
    url('^(?P<topic_id>\d+)/$', views.topic, name='lbforum_topic'),
    url('^(?P<topic_id>\d+)/delete/$', views.delete_topic,
        name='lbforum_delete_topic'),
    url('^(?P<topic_id>\d+)/update_topic_attr_as_not/(?P<attr>\w+)/$',
        views.update_topic_attr_as_not,
        name='lbforum_update_topic_attr_as_not'),
    url('^new/(?P<forum_id>\d+)/$', views.new_post, name='lbforum_new_topic'),
)

post_patterns = patterns(
    '',
    url('^(?P<post_id>\d+)/$', views.post, name='lbforum_post'),
    url('^(?P<post_id>\d+)/edit/$', views.edit_post, name='lbforum_post_edit'),
    url('^(?P<post_id>\d+)/delete/$', views.delete_post,
        name='lbforum_post_delete'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='lbforum_index'),
    url(r'^recent/$', views.recent, name='lbforum_recent'),
    (r'^forum/', include(forum_patterns)),
    (r'^topic/', include(topic_patterns)),
    url('^reply/new/(?P<topic_id>\d+)/$', views.new_post,
        name='lbforum_new_replay'),
    (r'^post/', include(post_patterns)),
    url('^user/(?P<user_id>\d+)/topics/$', views.user_topics,
        name='lbforum_user_topics'),
    url('^user/(?P<user_id>\d+)/posts/$', views.user_posts,
        name='lbforum_user_posts'),
    url(r'^lang.js$', direct_to_template, {'template': 'lbforum/lang.js'},
        name='lbforum_lang_js'),
    url('^markitup_preview/$', views.markitup_preview,
        name='markitup_preview'),
)

urlpatterns += patterns(
    '',
    url(r'^account/$', login_required(accountviews.profile),
        name='lbforum_account_index'),
    url(r'^account/signature/$', accountviews.signature,
        name='lbforum_signature'),
    url(r'^user/(?P<user_id>\d+)/$', login_required(accountviews.profile),
        name='lbforum_user_profile'),
)

urlpatterns += patterns(
    'simpleavatar.views',
    url('^account/avatar/change/$', 'change',
        {'template_name': 'lbforum/account/avatar/change.html'},
        name='lbforum_avatar_change'),
    (r'^accounts/avatar/', include('simpleavatar.urls')),
)

lbforum/models.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from base64 import b64encode, b64decode
import pickle

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from django.conf import settings

from attachments.models import Attachment
from onlineuser.models import Online


class Config(models.Model):
    key = models.CharField(max_length=255)  # PK
    value = models.CharField(max_length=255)


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default='')
    ordering = models.PositiveIntegerField(default=1)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ('-ordering', 'created_on')

    def __unicode__(self):
        return self.name


class Forum(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=110)
    description = models.TextField(default='')
    ordering = models.PositiveIntegerField(default=1)
    category = models.ForeignKey(Category)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    num_topics = models.IntegerField(default=0)
    num_posts = models.IntegerField(default=0)

    last_post = models.CharField(max_length=255, blank=True)  # pickle obj

    class Meta:
        verbose_name = _("Forum")
        verbose_name_plural = _("Forums")
        ordering = ('ordering', '-created_on')

    def _count_nums_topic(self):
        return self.topic_set.all().count()

    def _count_nums_post(self):
        num_posts = self.topic_set.all().aggregate(Sum('num_replies'))
        return num_posts['num_replies__sum'] or 0

    def get_last_post(self):
        if not self.last_post:
            return {}
        return pickle.loads(b64decode(self.last_post))

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_forum', (), {'forum_slug': self.slug})

    def __unicode__(self):
        return self.name

    def update_state_info(self, commit=True):
        self.num_topics = self._count_nums_topic()
        self.num_posts = self._count_nums_post()
        if self.num_topics:
            last_post = Post.objects.all().filter(topic__forum=self)
            last_post = last_post.order_by('-created_on')[0]
            self.last_post = gen_last_post_info(last_post)
        else:
            self.last_post = ''
        if commit:
            self.save()


class TopicType(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_('Forum'))
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True, default='')

    def __unicode__(self):
        return self.name


class TopicManager(models.Manager):
    def get_query_set(self):
        return super(TopicManager, self).get_query_set().filter(hidden=False)

LEVEL_CHOICES = (
    (30, _('Default')),
    (60, _('Distillate')),
)


class Topic(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_('Forum'))
    topic_type = models.ForeignKey(TopicType, verbose_name=_('Topic Type'),
            blank=True, null=True)
    posted_by = models.ForeignKey(User)

    #TODO ADD TOPIC POST.
    post = models.ForeignKey('Post', verbose_name=_('Post'),
                             related_name='topics_', blank=True, null=True)
    subject = models.CharField(max_length=999)
    num_views = models.IntegerField(default=0)
    num_replies = models.PositiveSmallIntegerField(default=0)  # posts...
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_reply_on = models.DateTimeField(auto_now_add=True)
    last_post = models.CharField(max_length=255, blank=True)  # pickle obj

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)
    need_replay = models.BooleanField(default=False)  # need_reply :-)
    need_reply_attachments = models.BooleanField(default=False)

    #Moderation features
    closed = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
    level = models.SmallIntegerField(choices=LEVEL_CHOICES, default=30)

    objects = TopicManager()

    class Meta:
        ordering = ('-last_reply_on',)  # '-sticky'
        get_latest_by = ('created_on')
        verbose_name = _("Topic")
        verbose_name_plural = _("Topics")

    def __unicode__(self):
        return self.subject

    def count_nums_replies(self):
        return self.posts.all().count()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_topic', (), {'topic_id': self.id})

    def get_last_post(self):
        if not self.last_post:
            return {}
        return pickle.loads(b64decode(self.last_post))

    def has_replied(self, user):
        if user.is_anonymous():
            return False
        return Post.objects.filter(posted_by=user, topic=self).count()

    def update_state_info(self, commit=True):
        self.num_replies = self.count_nums_replies()
        last_post = self.posts.order_by('-created_on')[0]
        self.last_post = gen_last_post_info(last_post)
        self.save()
        if commit:
            self.save()

FORMAT_CHOICES = (
    ('bbcode', _('BBCode')),
    ('html', _('Html')),
)


class Post(models.Model):
    topic = models.ForeignKey(Topic, verbose_name=_('Topic'), related_name='posts')
    posted_by = models.ForeignKey(User)
    poster_ip = models.IPAddressField()
    topic_post = models.BooleanField(default=False)

    format = models.CharField(max_length=20, default='bbcode')  # user name
    message = models.TextField()
    attachments = models.ManyToManyField(Attachment, blank=True)

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    edited_by = models.CharField(max_length=255, blank=True)  # user name

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-created_on',)
        get_latest_by = ('created_on', )

    def __unicode__(self):
        return self.message[:80]

    def subject(self):
        if self.topic_post:
            return _('Topic: %s') % self.topic.subject
        return _('Re: %s') % self.topic.subject

    def file_attachments(self):
        return self.attachments.filter(is_img=False)

    def img_attachments(self):
        return self.attachments.filter(is_img=True)

    def update_attachments_flag(self):
        self.has_attachments = self.file_attachments().count() > 0
        self.has_imgs = self.img_attachments().count() > 0
        self.save()
        if self.topic_post:
            t = self.topic
            t.has_attachments = self.has_attachments
            t.has_imgs = self.has_imgs
            t.save()

    def update_attachments(self, attachment_ids):
        self.attachments.clear()
        for attachment_id in attachment_ids:
            try:
                attachment = Attachment.objects.get(pk=attachment_id)
            except:
                continue
            attachment.activated = True
            attachment.save()
            self.attachments.add(attachment)
        self.update_attachments_flag()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_post', (), {'post_id': self.pk})

    def get_absolute_url_ext(self):
        topic = self.topic
        post_idx = topic.posts.filter(created_on__lte=self.created_on).count()
        page = (post_idx - 1) / settings.CTX_CONFIG['TOPIC_PAGE_SIZE'] + 1
        return '%s?page=%s#p%s' % (topic.get_absolute_url(), page, self.pk)


class LBForumUserProfile(models.Model):
    user = models.OneToOneField(User, related_name='lbforum_profile',
                                verbose_name=_('User'))
    last_activity = models.DateTimeField(auto_now_add=True)
    userrank = models.CharField(max_length=30, default="Junior Member")
    last_posttime = models.DateTimeField(auto_now_add=True)
    signature = models.CharField(max_length=1000, blank=True)

    def __unicode__(self):
        return self.user.username

    def get_total_posts(self):
        return self.user.post_set.count()

    def get_absolute_url(self):
        return self.user.get_absolute_url()


#### do smoe connect ###
def gen_last_post_info(post):
    last_post = {
        'posted_by': post.posted_by.username,
        'update': post.created_on
    }
    return b64encode(pickle.dumps(last_post, pickle.HIGHEST_PROTOCOL))


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        LBForumUserProfile.objects.create(user=instance)


def update_topic_on_post(sender, instance, created, **kwargs):
    if created:
        t = instance.topic
        t.last_post = gen_last_post_info(instance)
        t.last_reply_on = instance.created_on
        t.num_replies += 1
        t.save()
        p = instance.posted_by.lbforum_profile
        p.last_posttime = instance.created_on
        p.save()


def update_forum_on_post(sender, instance, created, **kwargs):
    if created:
        instance.topic.forum.last_post = gen_last_post_info(instance)
        instance.topic.forum.num_posts += 1
        instance.topic.forum.save()


def update_forum_on_topic(sender, instance, created, **kwargs):
    if created:
        instance.forum.num_topics += 1
        instance.forum.save()


def update_user_last_activity(sender, instance, created, **kwargs):
    if instance.user:

lbforum/templates/lbforum/widgets/categories_and_forums.html
{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}
{% for category in categories %}
<div class="main-subhead">
    <h2 class="hn"><span>{{ category }}</span></h2>
    <p class="item-summary"> 
        <span>
            <strong class="info-topics">{% trans "topics" %}</strong>,
            <strong class="info-posts">{% trans "posts" %}</strong>, 
            <strong class="info-lastpost">{% trans "last post" %}</strong>
        </span> 
    </p>
</div>
<div class="main-content main-category">
    {% for forum in category.forum_set.all %}
    <div id="forum" class="main-item {% cycle 'odd' 'even' %} {% if forloop.first %}main-item1{% endif %}">
        <span class="icon "><!-- --></span>

        <div class="item-subject">
            <h3 class="hn"><a href="{% url lbforum_forum forum.slug %}"><span> {{forum}} </span></a></h3>
            <p>{{ forum.description }}</p>
        </div>

        <ul class="item-info">
            <li class="info-topics">
                <strong>{{ forum.num_topics }} </strong> <span class="label">{% trans "topics" %}</span>
            </li>
            <li class="info-posts">
                <strong>{{ forum.num_posts }} </strong> <span class="label">{% trans "posts" %}</span>
            </li>
            <li class="info-lastpost">
                <span class="label">{% trans "Last post" %}:</span>
                {% if forum.get_last_post %}
                  <strong>{{ forum.get_last_post.update|lbtimesince }}</strong> 
                  <cite>by {{ forum.get_last_post.posted_by }}</cite>
                {% endif %}
            </li>
        </ul>
    </div>
    {% endfor %}
</div>
{% endfor %}

lbforum/templates/lbforum/widgets/lbf_status.html
{% load i18n %}
<div id="brd-stats" class="gen-content">
    <h2 class="hn"><span>Forum statistics</span></h2>
    <ul>
        <li class="st-users">
            <span>{% trans "Total number of registered users" %}: <strong>{{ total_users }} </strong></span>
        </li>
        <li class="st-users">
            <span>{% trans "Newest registered user" %}:
                <strong>
                    <a href="{% url lbforum_user_profile last_registered_user.pk %}">
                        {{ last_registered_user.username }}
                    </a>
                </strong>
            </span>
        </li>
        <li class="st-activity">
            <span>{% trans "Total number of topics" %}: <strong>{{ total_topics }}</strong></span>
        </li>
        <li class="st-activity">
            <span>{% trans "Total number of posts" %}: <strong> {{ total_posts }} </strong></span>
        </li>
    </ul>
</div>

lbforum/templates/lbforum/widgets/onlineinfos.html
{% load i18n %}
<div class="gen-content" id="brd-online">
    <h3 class="hn">
		<span>{% trans "Currently online" %} <strong> {{ total_onlines }} </strong> ( <strong> {{ total_onlines_guest }} </strong> {% trans "guests" %}, <strong>{{ total_onlines_user }}</strong> {% trans "registered user" %} )</span>
	</h3>
    <p>
        {% for o in online_users %} <a href="{% url lbforum_user_profile o.user_id %}">{{o.username}}</a> {% endfor %}
	</p>
</div>