lbforum/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from lbforum import views, accountviews

forum_patterns = patterns(
    '',
    url(r'^(?P<forum_slug>\w+)/$', views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/$',
        views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/(?P<topic_type2>\w+)/$',
        views.forum, name='lbforum_forum'),
)

topic_patterns = patterns(
    '',
    url('^(?P<topic_id>\d+)/$', views.topic, name='lbforum_topic'),
    url('^(?P<topic_id>\d+)/delete/$', views.delete_topic,
        name='lbforum_delete_topic'),
    url('^(?P<topic_id>\d+)/update_topic_attr_as_not/(?P<attr>\w+)/$',
        views.update_topic_attr_as_not,
        name='lbforum_update_topic_attr_as_not'),
    url('^new/(?P<forum_id>\d+)/$', views.new_post, name='lbforum_new_topic'),
)

post_patterns = patterns(
    '',
    url('^(?P<post_id>\d+)/$', views.post, name='lbforum_post'),
    url('^(?P<post_id>\d+)/edit/$', views.edit_post, name='lbforum_post_edit'),
    url('^(?P<post_id>\d+)/delete/$', views.delete_post,
        name='lbforum_post_delete'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='lbforum_index'),
    url(r'^recent/$', views.recent, name='lbforum_recent'),
    (r'^forum/', include(forum_patterns)),
    (r'^topic/', include(topic_patterns)),
    url('^reply/new/(?P<topic_id>\d+)/$', views.new_post,
        name='lbforum_new_replay'),
    (r'^post/', include(post_patterns)),
    url('^user/(?P<user_id>\d+)/topics/$', views.user_topics,
        name='lbforum_user_topics'),
    url('^user/(?P<user_id>\d+)/posts/$', views.user_posts,
        name='lbforum_user_posts'),
    url(r'^lang.js$', direct_to_template, {'template': 'lbforum/lang.js'},
        name='lbforum_lang_js'),
    url('^markitup_preview/$', views.markitup_preview,
        name='markitup_preview'),
)

urlpatterns += patterns(
    '',
    url(r'^account/$', login_required(accountviews.profile),
        name='lbforum_account_index'),
    url(r'^account/signature/$', accountviews.signature,
        name='lbforum_signature'),
    url(r'^user/(?P<user_id>\d+)/$', login_required(accountviews.profile),
        name='lbforum_user_profile'),
)

urlpatterns += patterns(
    'simpleavatar.views',
    url('^account/avatar/change/$', 'change',
        {'template_name': 'lbforum/account/avatar/change.html'},
        name='lbforum_avatar_change'),
    (r'^accounts/avatar/', include('simpleavatar.urls')),
)

lbforum/forms.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from datetime import datetime

from django import forms
from django.utils.translation import ugettext_lazy as _

from models import Topic, Post, TopicType
from models import LBForumUserProfile

FORUM_ORDER_BY_CHOICES = (
    ('-last_reply_on', _('Last Reply')),
    ('-created_on', _('Last Topic')),
)


class ForumForm(forms.Form):
    order_by = forms.ChoiceField(label=_('Order By'), choices=FORUM_ORDER_BY_CHOICES, required=False)


class PostForm(forms.ModelForm):
    topic_type = forms.ChoiceField(label=_('Topic Type'), required=False)
    subject = forms.CharField(label=_('Subject'), widget=forms.TextInput(attrs={'size': '80'}))
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(attrs={'cols': '95', 'rows': '14'}))
    attachments = forms.Field(label=_('Attachments'), required=False, widget=forms.SelectMultiple())
    need_replay = forms.BooleanField(label=_('Need Reply'), required=False)
    need_reply_attachments = forms.BooleanField(label=_('Attachments Need Reply'), required=False)

    class Meta:
        model = Post
        fields = ('message',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic = kwargs.pop('topic', None)
        self.forum = kwargs.pop('forum', None)
        self.ip = kwargs.pop('ip', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.forum = self.instance.topic.forum
        topic_types = self.forum.topictype_set.all()
        self.fields['topic_type'].choices = [(tp.id, tp.name) for tp in topic_types]
        self.fields['topic_type'].choices.insert(0, (('', '--------')))
        self.fields.keyOrder = ['topic_type', 'subject', 'message', 'attachments', 'need_replay',
                'need_reply_attachments']


class EditPostForm(PostForm):
    def __init__(self, *args, **kwargs):
        super(EditPostForm, self).__init__(*args, **kwargs)
        self.initial['subject'] = self.instance.topic.subject
        self.initial['need_replay'] = self.instance.topic.need_replay
        self.initial['need_reply_attachments'] = self.instance.topic.need_reply_attachments
        if self.instance.topic.topic_type:
            self.initial['topic_type'] = self.instance.topic.topic_type.id
        if not self.instance.topic_post:
            self.fields['subject'].required = False

    def save(self):
        post = self.instance
        post.message = self.cleaned_data['message']
        post.updated_on = datetime.now()
        post.edited_by = self.user.username
        attachments = self.cleaned_data['attachments']
        post.update_attachments(attachments)
        post.save()
        if post.topic_post:
            post.topic.subject = self.cleaned_data['subject']
            post.topic.need_replay = self.cleaned_data['need_replay']
            post.topic.need_reply_attachments = self.cleaned_data['need_reply_attachments']
            topic_type = self.cleaned_data['topic_type']
            if topic_type:
                topic_type = TopicType.objects.get(id=topic_type)
            else:
                topic_type = None
            post.topic.topic_type = topic_type
            post.topic.save()
        return post


class NewPostForm(PostForm):
    def __init__(self, *args, **kwargs):
        super(NewPostForm, self).__init__(*args, **kwargs)
        if self.topic:
            self.fields['subject'].required = False

    def save(self):
        topic_post = False
        if not self.topic:
            topic_type = self.cleaned_data['topic_type']
            if topic_type:
                topic_type = TopicType.objects.get(id=topic_type)
            else:
                topic_type = None
            topic = Topic(forum=self.forum,
                          posted_by=self.user,
                          subject=self.cleaned_data['subject'],
                          need_replay=self.cleaned_data['need_replay'],
                          need_reply_attachments=self.cleaned_data['need_reply_attachments'],
                          topic_type=topic_type,
                          )
            topic_post = True
            topic.save()
        else:
            topic = self.topic
        post = Post(topic=topic, posted_by=self.user, poster_ip=self.ip,
                    message=self.cleaned_data['message'], topic_post=topic_post)
        post.save()
        if topic_post:
            topic.post = post
            topic.save()
        attachments = self.cleaned_data['attachments']
        post.update_attachments(attachments)
        return post


class SignatureForm(forms.ModelForm):
    signature = forms.CharField(label=_('Message'), required=False,
            widget=forms.Textarea(attrs={'cols': '65', 'rows': '4'}))

    class Meta:
        model = LBForumUserProfile
        fields = ('signature',)

lbforum/templates/lbforum/account/base.html
{% extends 'lbforum/base.html' %}

{% load i18n %}
{% load lbforum_tags %}
{% load lbforum_filters %}
{% load avatar_tags %}

{% block title %} {{ LBFORUM_TITLE }} - {{ LBFORUM_SUB_TITLE }} {% endblock %}

{% block content %}
	<div id="replybox">
		<div id="actionbox">
		</div>
	</div>
	<div id="brd-wrap" class="brd">
		<div id="{% block brd-page-id %}{% endblock %}" class="brd-page menu-page">
			{% include 'lbforum/inc_header.html' %}
			{% include 'lbforum/inc_announce.html' %}
			<div class="hr"><hr/></div>
            <div id="brd-crumbs-top" class="crumbs gen-content">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span> &raquo; </span>
                        {% firstof view_user user %}{% trans "'s profile" %}
                    </span> 
                </p>
            </div>

			<div class="main-wrapper" id="brd-main">
				<div class="main-menu gen-content">
					<ul>
						<li class="item1 {% block main_menu_profile_class %}{% endblock %}">
                            {% if view_only %}
                            <a href="{% url lbforum_account_index %}"><span>{% trans "Introduction" %}</span></a>
                            {% endif %}
                            {% if not view_only %}
                            <a href="{% url lbforum_user_profile user.pk %}"><span>{% trans "Introduction" %}</span></a>
                            {% endif %}
                        </li>
                        {% if not view_only %}
                        <li class="{% block main_menu_avatar_class %}{% endblock %}">
                            <a href="{% url lbforum_avatar_change %}"><span>{% trans "Avatar" %}</span></a>
                        </li>
                        {% endif %}
                        {% if not view_only %}
                        <li class="{% block main_menu_sig_class %}{% endblock %}">
                            <a href="{% url lbforum_signature %}"><span>{% trans "Signature" %}</span></a>
                        </li>
                        {% endif %}
					</ul>
				</div>

				<div class="main-head">
					<h1 class="hn"><span>{% block main_head %}{% endblock %}</span></h1>
				</div>
				<div class="main-subhead">
					<h2 class="hn"><span>{% block main_subhead %}{% endblock %}</span></h2>
				</div>
				<div class="main-content main-frm">
                {% block account_main_content %}
                {% endblock %}
				</div>
			</div>

			<div class="crumbs gen-content" id="brd-crumbs-end">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span> &raquo; </span>
                        {% firstof view_user user %}{% trans "'s profile" %}
                    </span> 
                </p>
			</div>
			<div class="hr"><hr /></div>
			{% include 'lbforum/inc_copyright.html' %}
		</div>
	</div>
    {% block content_footer %}{% endblock %}
{% endblock %}

lbforum/templates/lbforum/account/profile.html
{% extends 'lbforum/account/base.html' %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}
{% load avatar_tags %}

{% block title %}
	{{ LBFORUM_TITLE }} - {% blocktrans %}{{ view_user }}'s profile{% endblocktrans %}
{% endblock %}

{% block brd-page-id %}brd-profile-about{% endblock %}

{% block main_menu_profile_class %}active{% endblock %}
{% block main_head %}{% blocktrans %}{{ view_user }}'s profile{% endblocktrans %}{% endblock %}
{% block main_subhead %}{% trans "Welcome to your profile" %}{% endblock %}

{% block account_main_content %}
    {% if user == view_user %}
	<p class="content-options options">
		<span class="item1"><a href="{% url auth_password_change %}">{% trans "Change your password" %}</a></span> 
	</p>
    {% endif %}
    
	<div class="profile ct-group data-group vcard">
		<div class="ct-set data-set set1">
			<div class="ct-box data-box">
				<ul class="user-ident ct-legend">
                    <li class="username fn nickname"><strong>{{ view_user }}</strong></li>
					<li class="usertitle"><span>{% trans "Member" %}</span></li>					
					<li class="useravatar">{% avatar view_user %}</li>
				</ul>
				<ul class="data-list">
					<li><span>{% trans "Registered" %}: <strong>{{view_user.date_joined|date:"Y-m-d"}}</strong></span></li>
					<li><span>{% trans "Last login" %}: <strong>{{view_user.last_login|date:"Y-m-d"}}</strong></span></li>
                    <li><span>{% trans "Topics" %}: <strong>{{view_user.topic_set.all.count}}</strong> </span></li>
					<li><span>{% trans "Posts" %}: <strong>{{view_user.post_set.all.count}}</strong> </span></li>
				</ul>
			</div>
		</div>
        <div class="ct-set data-set set2">
            <div class="ct-box data-box">
                <h3 class="ct-legend hn"><span>{% trans "Posts and topics" %}</span></h3>
                <p class="options">
                    <span class="item1"><a href="{% url lbforum_user_posts view_user.pk %}">{% blocktrans %}View all {{view_user}}'s posts{% endblocktrans %}</a></span>
                    <span><a href="{% url lbforum_user_topics view_user.pk %}">{% blocktrans %}View all {{view_user}}'s topics{% endblocktrans %}</a></span>
                </p>
            </div>
        </div>
	</div>
{% endblock %}

lbforum/templates/lbforum/account/signature.html
{% extends 'lbforum/account/base.html' %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% block title %}
	{{ LBFORUM_TITLE }} - {% blocktrans %}{{ user }}'s profile{% endblocktrans %} : {% trans "Signature" %}
{% endblock %}

{% block extra_header %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/scripts/markitup/skins/markitup/style.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/scripts/markitup/sets/bbcode/style.css" />
{% endblock %}

{% block brd-page-id %}brd-profile-signature{% endblock %}

{% block main_menu_sig_class %}active{% endblock %}
{% block main_head %}{% blocktrans %}{{ user }}'s profile{% endblocktrans %} : {% trans "Signature" %}{% endblock %}
{% block main_subhead %}{% trans "Create or modify a signature for display in your posts" %}{% endblock %}

{% block account_main_content %}
    {% if form.errors %}
        <div class="ct-box error-box" id="req-msg">
            <p class="errornote"> {% trans "Please correct the errors below." %}  </p>
            {{ form|form_all_error }}
        </div>
    {% endif %}
    <form enctype="multipart/form-data" method="POST" action="">
        <div class="hidden">
            {% csrf_token %}
        </div>
        <fieldset class="frm-group group1">
            <legend class="group-legend"><strong>{% trans "Signature" %}</strong></legend>
            <div class="ct-set info-set set1">
                <div class="ct-box info-box">
                    <h3 class="ct-legend hn">{% trans "Current signature" %}</h3>
                    <div class="sig-demo">{{ user.lbforum_profile.signature|bbcode|safe }}</div>
                </div>
            </div>
            <div class="txt-set set2">
                <div class="txt-box textarea">
                    <label for="fld1">
                        <span>{% trans "Compose signature" %}:</span>
                    </label>
                    <div class="txt-input">
                        <span class="fld-input">
                            <small>{% trans "Maximum size 400 characters long and 4 lines high." %}</small>
                            {{ form.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="frm-buttons">
            <span class="submit">
                <input type="submit" name="update" value="{% trans "Update profile" %}" />
            </span>
        </div>
    </form>
{% endblock %}

{% block content_footer %}
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/markitup/jquery.markitup.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/markitup/sets/bbcode/set.js"></script>
    <script type="text/javascript">
        mySettings['previewParserPath']='{% url markitup_preview %}';
	    $("#id_signature").markItUp(mySettings);
    </script>
{% endblock %}

lbforum/templates/lbforum/account/user_posts.html
{% extends "lbforum/base.html" %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% block title %}{{  block.super }}{% endblock %}

{% block content %}
	<div id="actionbox">
	</div>  

	<div id="brd-wrap" class="brd">
		<div id="brd-searchposts" class="brd-page paged-page">
			{% include 'lbforum/inc_header.html' %}
			{% include 'lbforum/inc_announce.html' %}

			<div class="hr"><hr /></div>

			<div class="crumbs gen-content" id="brd-crumbs-top">
				<p>
					<span class="crumb crumbfirst">
						<a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
					</span> 
					<span class="crumb crumblast">
						<span>&raquo;</span>
						{% blocktrans %}Posts by {{view_user}}{% endblocktrans %}
					</span> 
				</p>
			</div>

			<div id="brd-main">
				<div class="main-pagepost gen-content" id="brd-pagepost-top">
					{% load pagination_tags %}
					{% autopaginate posts TOPIC_PAGE_SIZE %}
					{% paginate %}
					<p class="posting">
					</p>
				</div>
				<div class="main-head">
					<h1 class="hn">
						<span>
							{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
							<small></small>
						</span>
					</h1>
				</div>

				<div class="main-pagehead">
					<h2 class="hn"><span><span class="item-info">{% trans "Posts" %} [ {% page_range_info page_obj %} ]</span></span></h2>
				</div>
				<div class="main-content main-topic" id="forum">
					{% for post in posts %}     
						<div class="post {% cycle 'odd' 'even' %} {{forloop|post_style}}" id="p{{post.pk}}">
							<div class="posthead">
								<h3 class="hn post-ident">
									<span class="post-num">{% page_item_idx page_obj forloop %}</span>
									<span class="post-byline">
										<span>{% trans "Topic by" %} </span>
										<a href="{% url lbforum_user_profile post.posted_by.pk %}">{{post.posted_by.username}}</a>
									</span>
									<span class="post-link">
										<a href="{{ post.get_absolute_url }}" title="Permanent link to this post" rel="bookmark" class="permalink">{{ post.created_on|lbtimesince }}</a>
									</span>
								</h3>
								<h4 class="hn post-title">
									<span>
										<a href="{{ post.topic.get_absolute_url }}" title="Permanent link to this topic" rel="bookmark" class="permalink">{{ post.subject }}</a> 
										<small>({{ post.topic.num_replies|add:"-1" }} {% trans "replies" %}, {% trans "posted in" %} <a href="{{ post.topic.forum.get_absolute_url }}">{{ post.topic.forum }}</a>)</small>
									</span>
								</h4>
							</div>
							<div class="postbody">
								<div class="post-author">
									<ul class="author-ident">
										<li class="username"> <a href="{% url lbforum_user_profile post.posted_by.pk %}">{{post.posted_by.username}}</a> </li>
									</ul>
								</div>
								<div class="post-entry">
									<div class="entry-content">
										<p>{{ post.message|bbcode|safe }}</p>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>

				<div class="main-options gen-content">
					<p class="options"></p>
				</div>

				<div class="main-pagepost gen-content" id="brd-pagepost-end">
					{% paginate %}	
					<p class="posting">
					</p>
				</div>

			</div>

			<div class="crumbs gen-content" id="brd-crumbs-end">
				<p>
					<span class="crumb crumbfirst">
						<a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
					</span> 
					<span class="crumb crumblast">
						<span>&raquo;</span>
						{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
					</span> 
				</p>
			</div>

			<div class="hr"><hr /></div>

			{% include 'lbforum/inc_copyright.html' %}

		</div>
	</div>
{% endblock %}

lbforum/templates/lbforum/account/user_topics.html
{% extends "lbforum/base.html" %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% block title %}{{  block.super }}{% endblock %}

{% block content %}
    <div id="actionbox">
    </div>  

    <div id="brd-wrap" class="brd">
        <div id="brd-searchtopics" class="brd-page paged-page">
            {% include 'lbforum/inc_header.html' %}
            {% include 'lbforum/inc_announce.html' %}

            <div class="hr"><hr /></div>

            <div class="crumbs gen-content" id="brd-crumbs-top">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span>&raquo;</span>
						{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                    </span> 
                </p>
            </div>

            <div id="brd-main">
                <div class="main-pagepost gen-content" id="brd-pagepost-top">
                    {% load pagination_tags %}
                    {% autopaginate topics 50 %}
                    {% paginate %}
                    <p class="posting">
                    </p>
                </div>
                <div class="main-head">
                    <h1 class="hn">
                        <span>
							{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                            <small></small>
                        </span>
                    </h1>
                </div>

                {% include 'lbforum/inc_topic_list.html' %}

                <div class="main-options gen-content">
                    <p class="options"></p>
                </div>

                <div class="main-pagepost gen-content" id="brd-pagepost-end">
                    {% paginate %}	
                    <p class="posting">
                    </p>
                </div>

            </div>

            <div class="crumbs gen-content" id="brd-crumbs-end">
                <p>
                    <span class="crumb crumbfirst">
                        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
                    </span> 
                    <span class="crumb crumblast">
                        <span>&raquo;</span>
						{% blocktrans %}Topics by {{view_user}}{% endblocktrans %}
                    </span> 
                </p>
            </div>

            <div class="hr"><hr /></div>

            {% include 'lbforum/inc_copyright.html' %}

        </div>
    </div>
{% endblock %}