lbforum/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required

from lbforum import views, accountviews

forum_patterns = patterns(
    '',
    url(r'^(?P<forum_slug>\w+)/$', views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/$',
        views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>\w+)/(?P<topic_type>\w+)/(?P<topic_type2>\w+)/$',
        views.forum, name='lbforum_forum'),
)

topic_patterns = patterns(
    '',
    url('^(?P<topic_id>\d+)/$', views.topic, name='lbforum_topic'),
    url('^(?P<topic_id>\d+)/delete/$', views.delete_topic,
        name='lbforum_delete_topic'),
    url('^(?P<topic_id>\d+)/update_topic_attr_as_not/(?P<attr>\w+)/$',
        views.update_topic_attr_as_not,
        name='lbforum_update_topic_attr_as_not'),
    url('^new/(?P<forum_id>\d+)/$', views.new_post, name='lbforum_new_topic'),
)

post_patterns = patterns(
    '',
    url('^(?P<post_id>\d+)/$', views.post, name='lbforum_post'),
    url('^(?P<post_id>\d+)/edit/$', views.edit_post, name='lbforum_post_edit'),
    url('^(?P<post_id>\d+)/delete/$', views.delete_post,
        name='lbforum_post_delete'),
)

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='lbforum_index'),
    url(r'^recent/$', views.recent, name='lbforum_recent'),
    (r'^forum/', include(forum_patterns)),
    (r'^topic/', include(topic_patterns)),
    url('^reply/new/(?P<topic_id>\d+)/$', views.new_post,
        name='lbforum_new_replay'),
    (r'^post/', include(post_patterns)),
    url('^user/(?P<user_id>\d+)/topics/$', views.user_topics,
        name='lbforum_user_topics'),
    url('^user/(?P<user_id>\d+)/posts/$', views.user_posts,
        name='lbforum_user_posts'),
    url(r'^lang.js$', direct_to_template, {'template': 'lbforum/lang.js'},
        name='lbforum_lang_js'),
    url('^markitup_preview/$', views.markitup_preview,
        name='markitup_preview'),
)

urlpatterns += patterns(
    '',
    url(r'^account/$', login_required(accountviews.profile),
        name='lbforum_account_index'),
    url(r'^account/signature/$', accountviews.signature,
        name='lbforum_signature'),
    url(r'^user/(?P<user_id>\d+)/$', login_required(accountviews.profile),
        name='lbforum_user_profile'),
)

urlpatterns += patterns(
    'simpleavatar.views',
    url('^account/avatar/change/$', 'change',
        {'template_name': 'lbforum/account/avatar/change.html'},
        name='lbforum_avatar_change'),
    (r'^accounts/avatar/', include('simpleavatar.urls')),
)

lbforum/forms.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
from datetime import datetime

from django import forms
from django.utils.translation import ugettext_lazy as _

from models import Topic, Post, TopicType
from models import LBForumUserProfile

FORUM_ORDER_BY_CHOICES = (
    ('-last_reply_on', _('Last Reply')),
    ('-created_on', _('Last Topic')),
)


class ForumForm(forms.Form):
    order_by = forms.ChoiceField(label=_('Order By'), choices=FORUM_ORDER_BY_CHOICES, required=False)


class PostForm(forms.ModelForm):
    topic_type = forms.ChoiceField(label=_('Topic Type'), required=False)
    subject = forms.CharField(label=_('Subject'), widget=forms.TextInput(attrs={'size': '80'}))
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(attrs={'cols': '95', 'rows': '14'}))
    attachments = forms.Field(label=_('Attachments'), required=False, widget=forms.SelectMultiple())
    need_replay = forms.BooleanField(label=_('Need Reply'), required=False)
    need_reply_attachments = forms.BooleanField(label=_('Attachments Need Reply'), required=False)

    class Meta:
        model = Post
        fields = ('message',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic = kwargs.pop('topic', None)
        self.forum = kwargs.pop('forum', None)
        self.ip = kwargs.pop('ip', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.forum = self.instance.topic.forum
        topic_types = self.forum.topictype_set.all()
        self.fields['topic_type'].choices = [(tp.id, tp.name) for tp in topic_types]
        self.fields['topic_type'].choices.insert(0, (('', '--------')))
        self.fields.keyOrder = ['topic_type', 'subject', 'message', 'attachments', 'need_replay',
                'need_reply_attachments']


class EditPostForm(PostForm):
    def __init__(self, *args, **kwargs):
        super(EditPostForm, self).__init__(*args, **kwargs)
        self.initial['subject'] = self.instance.topic.subject
        self.initial['need_replay'] = self.instance.topic.need_replay
        self.initial['need_reply_attachments'] = self.instance.topic.need_reply_attachments
        if self.instance.topic.topic_type:
            self.initial['topic_type'] = self.instance.topic.topic_type.id
        if not self.instance.topic_post:
            self.fields['subject'].required = False

    def save(self):
        post = self.instance
        post.message = self.cleaned_data['message']
        post.updated_on = datetime.now()
        post.edited_by = self.user.username
        attachments = self.cleaned_data['attachments']
        post.update_attachments(attachments)
        post.save()
        if post.topic_post:
            post.topic.subject = self.cleaned_data['subject']
            post.topic.need_replay = self.cleaned_data['need_replay']
            post.topic.need_reply_attachments = self.cleaned_data['need_reply_attachments']
            topic_type = self.cleaned_data['topic_type']
            if topic_type:
                topic_type = TopicType.objects.get(id=topic_type)
            else:
                topic_type = None
            post.topic.topic_type = topic_type
            post.topic.save()
        return post


class NewPostForm(PostForm):
    def __init__(self, *args, **kwargs):
        super(NewPostForm, self).__init__(*args, **kwargs)
        if self.topic:
            self.fields['subject'].required = False

    def save(self):
        topic_post = False
        if not self.topic:
            topic_type = self.cleaned_data['topic_type']
            if topic_type:
                topic_type = TopicType.objects.get(id=topic_type)
            else:
                topic_type = None
            topic = Topic(forum=self.forum,
                          posted_by=self.user,
                          subject=self.cleaned_data['subject'],
                          need_replay=self.cleaned_data['need_replay'],
                          need_reply_attachments=self.cleaned_data['need_reply_attachments'],
                          topic_type=topic_type,
                          )
            topic_post = True
            topic.save()
        else:
            topic = self.topic
        post = Post(topic=topic, posted_by=self.user, poster_ip=self.ip,
                    message=self.cleaned_data['message'], topic_post=topic_post)
        post.save()
        if topic_post:
            topic.post = post
            topic.save()
        attachments = self.cleaned_data['attachments']
        post.update_attachments(attachments)
        return post


class SignatureForm(forms.ModelForm):
    signature = forms.CharField(label=_('Message'), required=False,
            widget=forms.Textarea(attrs={'cols': '65', 'rows': '4'}))

    class Meta:
        model = LBForumUserProfile
        fields = ('signature',)

lbforum/templates/lbforum/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

{% block html_declare %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
{% endblock %}

	<head>
		<title>
			{% block title %} {{ LBFORUM_TITLE }} - {{ LBFORUM_SUB_TITLE }} {% endblock %}
		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		{% include 'lbforum/inc_styles.html' %}
		{% block extra_header %}{% endblock %}
	</head>

	<body>
		{% block content %} {% endblock %}        
	</body>    
</html>

lbforum/templates/lbforum/forum.html
{% extends "lbforum/base.html" %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}
{% load djangohelper_tags %}

{% block title %}
    {{ forum }} - {{ topic_type }} - {{ topic_type2 }} - {{ LBFORUM_TITLE }}
{% endblock %}

{% block content %}
	<div id="actionbox">
	</div>  

	<div id="brd-wrap" class="brd">
		<div id="brd-viewforum" class="brd-page paged-page">
			{% include 'lbforum/inc_header.html' %}
			{% include 'lbforum/inc_announce.html' %}

			<div class="hr"><hr /></div>

			<div class="crumbs gen-content" id="brd-crumbs-top">
                {% include 'lbforum/inc_forum_brd_crumbs.html' %}
			</div>

<!-- brd-main begin -->
<div id="brd-main">
	<div class="main-pagepost gen-content" id="brd-pagepost-top">
		{% load pagination_tags %}
		{% autopaginate topics FORUM_PAGE_SIZE %}
		{% paginate %}
        <p class="posting">
            {% if user.is_authenticated %}
                <a class="newpost" href="{% url lbforum_new_topic forum.pk %}"><span>{% trans "Post new topic" %}</span></a>
            {% else %}
                {% trans "You must" %} <a href="{{ LOGIN_URL }}">{% trans "Login" %}</a> {% trans "or" %} <a href="{{ REGISTER_URL }}">{% trans "register" %}</a> {% trans "to post a topic" %}
            {% endif %} 
        </p>
	</div>
	<div class="main-head">
        <h1 class="hn"><span><a title="Permanent link to this forum." rel="bookmark" href="{% url lbforum_forum forum.slug %}" class="permalink">{{ forum }}</a> <small></small></span></h1>
	</div>

    {% include 'lbforum/inc_topic_list.html' %}

    <div class="main-options gen-content">
        <p class="options"></p>
    </div>

	<div class="main-pagepost gen-content" id="brd-pagepost-end">
        {% paginate %}	
		<p class="posting">
            {% if user.is_authenticated %}
                <a class="newpost" href="{% url lbforum_new_topic forum.pk %}"><span>{% trans "Post new topic" %}</span></a>
            {% else %}
                {% trans "You must" %} <a href="{{ LOGIN_URL }}">{% trans "Login" %}</a> {% trans "or" %} <a href="{{ REGISTER_URL }}">{% trans "register" %}</a> {% trans "to post a topic" %}
            {% endif %} 
        </p>
	</div>
</div>
<!-- brd-main ends -->


<div class="crumbs gen-content" id="brd-crumbs-end">
    <p id="forum_order_by">
        {% trans "Order By"%}:
        {{ form.order_by }}
    </p>
    {% include 'lbforum/inc_forum_brd_crumbs.html' %}
</div>

<div class="hr"><hr /></div>

{% include 'lbforum/inc_copyright.html' %}

  </div>
</div>

<script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/jquery.min.js"></script>
<script type="text/javascript">
    $('#id_order_by').change(function () {
        window.location.href="?order_by=" + $('#id_order_by').val() + "{% getvars request 'order_by'%}";
    })
</script>
{% endblock %}

lbforum/templates/lbforum/inc_announce.html
{% load i18n %}

{% if announcement %}
<div id="brd-announcement" class="gen-content">
    <div class="content">
        <strong>
            [{% trans "New Announcement" %}]
        </strong>
        <a href="#">  {{ announcement.subject }}</a>
        <p>{{ announcement.message }}</p>
    </div>
</div>
{% endif %}

{% if messages %}
<ul class="brd-messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

lbforum/templates/lbforum/inc_copyright.html
<div id="brd-about" class="gen-content">
    <p id="copyright">Powered by <strong><a href="http://github.com/vicalloy/LBForum">LBForum</a></strong></p>
    <p id="extensions-used">Copyright &copy; 2010 ~ 2013<a href="http://haoluobo.com/">vicalloy</a></p>
</div>

lbforum/templates/lbforum/inc_forum_brd_crumbs.html
<p>
    <span class="crumb crumbfirst">
        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
    </span> 
    <span class="crumb crumblast">
        <span>&raquo;</span>
        {{ forum }}
    </span> 
</p>

lbforum/templates/lbforum/inc_header.html
{% load i18n %}

<div id="brd-head" class="gen-content">
    <p id="brd-access"><a href="#brd-main">Skip to forum content</a></p>
    <p id="brd-title"><a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a></p>
    <p id="brd-desc">{{ LBFORUM_SUB_TITLE }}</p>
</div>

<div id="brd-navlinks" class="gen-content">
    <ul id="brd-navlinks-left">
		{% include 'lbforum/plugins/inc_header_left_links.html' %}
    </ul>
    <ul id="brd-navlinks-right">
        <li>
            <a href="#">{% trans "Search" %}</a>
        </li>
        {% if user.is_authenticated %}
        <li id="navprofile"><a href="{% url lbforum_account_index %}">{% trans "My profile" %}</a></li>
        <li id="navlogout"><a href="{{ LOGOUT_URL }}?next={% url lbforum_index %}">{% trans "Logout" %}</a></li>
        {% else %}
        <li id="navregister"><a href="{{ REGISTER_URL }}">{% trans "Register" %}</a></li>
        <li id="navlogin"><a href="{{ LOGIN_URL }}">{% trans "Login" %}</a></li>
        {% endif %}
    </ul>
</div>

<div id="brd-visit" class="gen-content">
    <p id="welcome">
        <span>
            {% if user.is_authenticated %}
            {% blocktrans %}Hello {{user}}{% endblocktrans %}, <a href='{{ LOGOUT_URL }}?next={% url lbforum_index %}'>{% trans "Logout" %}</a>
            {% else %}
            <a href="{{ LOGIN_URL }}">{% trans "Login" %}</a>
            |
            <a href="{{ REGISTER_URL }}">{% trans "Register" %}</a>
            {% endif %}
        </span>
    </p>
    <p id="visit-links" class="options">
    </p>
</div> 

lbforum/templates/lbforum/inc_new_post_brd_crumbs.html
{% load i18n %}
<p>
    <span class="crumb crumbfirst">
        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
    </span> 
    <span class="crumb">
        <span> &raquo; </span>
        <a href="{{ forum.get_absolute_url }}">{{ forum.name }}</a>
    </span> 
    {% if topic %}
    <span class="crumb">
        <span> &raquo; </span>
        <a href="{{ topic.get_absolute_url }}">{{ topic.subject }}</a>
    </span> 
    {% endif %}
    <span class="crumb crumblast">
        <span> &raquo; </span>
        {% if is_new_post %}{% trans "Post new" %}{% else %}{% trans "Edit" %}{% endif %} {{ post_type }}
    </span> 
</p>

lbforum/templates/lbforum/inc_styles.html
<link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/styles/Oxygen/Oxygen.css" />
<link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/styles/Oxygen/Oxygen_cs.css" />
<!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lbforum/styles/Oxygen/Oxygen_ie6.css" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lbforum/styles/Oxygen/Oxygen_ie7.css" /><![endif]-->

lbforum/templates/lbforum/inc_topic_brd_crumbs.html
<p>
    <span class="crumb crumbfirst">
        <a href="{% url lbforum_index %}">{{ LBFORUM_TITLE }}</a>
    </span> 
    <span class="crumb">
        <span> &raquo; </span>
        <a href="{{ topic.forum.get_absolute_url }}">{{ topic.forum.name }}</a>
    </span> 
    <span class="crumb crumblast">
        <span> &raquo; </span>
        {{ topic.subject }}
    </span> 
</p>

lbforum/templates/lbforum/post.html
{% extends "lbforum/base.html" %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% block title %}{{  block.super }}{% endblock %}

{% block extra_header %}
	<link href="{{ STATIC_URL }}lbforum/scripts/jquery.uploadify/uploadify.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/scripts/markitup/skins/markitup/style.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{{ STATIC_URL }}lbforum/scripts/markitup/sets/bbcode/style.css" />
{% endblock %}

{% block content %}
    <div id="actionbox">
    </div>  
    <div id="brd-wrap" class="brd">
        <div id="brd-viewforum" class="brd-page paged-page">
            {% include 'lbforum/inc_header.html' %}
            {% include 'lbforum/inc_announce.html' %}

            <div class="hr"><hr /></div>

            <div class="crumbs gen-content" id="brd-crumbs-top">
                {% include 'lbforum/inc_new_post_brd_crumbs.html' %}
            </div>
            <div class="main-wrapper" id="brd-main">
                <div class="main-head">
                    <h1 class="hn"><span>{% if is_new_post %}{% trans "Post new" %}{% else %}{% trans "Edit" %}{% endif %} {{ post_type }}</span></h1>
                </div>
                {% if preview %}
                    <div class="main-subhead">
                        <h2 class="hn"><span>{% trans "Preview your" %} {% if is_new_post %}{% trans "new" %}{% else %}{% trans "edited" %}{% endif %} {{ post_type }}</span></h2>
                    </div>
                    <div class="main-content main-frm" id="post-preview">
                        <div class="post singlepost">
                            <div class="posthead">
                                <h3 class="hn"><span class="post-num">#</span> <span class="post-byline"><span>{% trans "Topic by" %} </span><strong>{{ user.username }}</strong></span> <span class="post-link">{% now "Y-m-d H:i" %}</span></h3>
                            </div>
                            <div class="postbody">
                                <div class="post-entry">
                                    <div class="entry-content">
                                        <p>{{form.cleaned_data.message|bbcode|safe}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="main-subhead">
                    <h2 class="hn"><span>{% trans "Compose and post your" %} {% if is_new_post %}{% trans "new" %}{% else %}{% trans "edited" %}{% endif %} {{ post_type }}</span></h2>
                </div>
                <div class="main-content main-frm" id="post-form">
                    <p class="ct-options options">{% trans "You may use" %}: <span class="item1"><a title="Help with: BBCode" href="http://fluxbb.org/forums/help/bbcode/" class="exthelp">BBCode</a></span> <span><a title="Help with: Images" href="http://fluxbb.org/forums/help/img/" class="exthelp">Images</a></span> <span><a title="Help with: Smilies" href="http://fluxbb.org/forums/help/smilies/" class="exthelp">Smilies</a></span></p>
                    {% if form.errors %}
                        <div class="ct-box error-box" id="req-msg">
                            <p class="errornote"> {% trans "Please correct the errors below." %}  </p>
                            {{ form|form_all_error }}
                        </div>
                    {% endif %}
                    <form action="" accept-charset="utf-8" method="post" class="frm-form" id="afocus">
                        <div class="hidden" id="hidden_fields">
                            {% csrf_token %} 
                        </div>
                        <fieldset class="frm-group group1">
                            <legend class="group-legend"><strong>{% trans "Required information" %}</strong></legend>
                            {% if topic_post %}
                                <div class="sf-set set1">
                                    <div class="sf-box text required longtext">
                                        <label for="id_subject"><span>{% trans "Topic subject" %}: <em>({% trans "Required" %})</em></span></label><br/>
                                        <span class="fld-input">
                                            {{form.topic_type}} {{form.subject}}
                                        </span>
                                    </div>
                                </div>
                            {% endif %}
                            <div class="txt-set {% if topic %}set1{% else %}set2{% endif %}">
                                <div class="txt-box textarea required">
                                    <label for="id_message"><span>{% trans "Write message" %}: <em>({% trans "Required" %})</em></span></label>
                                    <div class="txt-input">
                                        <span class="fld-input">
                                            {{form.message}}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            {% if topic_post %}
                            <fieldset class="mf-set set3">
                                <legend><span>{% trans "Optional post settings" %}:</span></legend>
                                <div class="mf-box checkbox">
                                    <div class="mf-item">
                                        <span class="fld-input">
                                            {{form.need_replay}}
                                        </span> 
                                        <label for="fld3">{% trans "reply to see the post" %}</label>
                                    </div>
                                    <div class="mf-item">
                                        <span class="fld-input">
                                            {{form.need_reply_attachments}}
                                        </span> 
                                        <label for="fld3">{% trans "reply to see the attachments" %}</label>
                                    </div>
                                </div>
                            </fieldset>
                            {% endif %}
                            <fieldset class="mf-set set4">
                                <legend><span>{% trans "Attachments" %}:</span></legend>
                                <div class="mf-box checkbox">
									<div class="mf-item">

										<div id="uploadify" class="multi-file-upload">
											<input id="fileInput" name="file" type="file" />
										</div>

										<ul id="uploaded_files">
										</ul>
									</div>
                                </div>
                            </fieldset>
                        </fieldset>
                        <div class="frm-buttons">
                            <span class="submit"><input type="submit" value="{% trans "Submit" %}" name="submit"/></span>
                            <span class="submit"><input type="submit" value="{% trans "Preview" %}" name="preview"/></span>
                        </div>
                    </form>
                </div>
                {% if first_post %}
                    <div class="main-subhead">
                        <h2 class="hn"><span>{% trans "Topic review (newest first)" %}</span></h2>
                    </div>
                    <div class="main-content main-frm" id="topic-review">
                        <div class="post firstpost lastpost">
                            <div class="posthead">
                                <h3 class="hn post-ident">
                                    <span class="post-num">1</span> <span class="post-byline"><span>{% trans "Post by" %} </span><strong>{{ first_post.posted_by.username }}</strong></span> 
                                    <span class="post-link">{{ first_post.created_on|lbtimesince }}</span>
                                </h3>
                            </div>
                            <div class="postbody">
                                <div class="post-entry">
                                    <div class="entry-content">
                                        <p>{{ first_post.message|bbcode|safe }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="crumbs gen-content" id="brd-crumbs-end">
                {% include 'lbforum/inc_new_post_brd_crumbs.html' %}
            </div>
            <div class="hr"><hr /></div>
            {% include 'lbforum/inc_copyright.html' %}
        </div>
    </div>

    <script type="text/javascript" src="{% url lbforum_lang_js %}"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/jquery.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/markitup/jquery.markitup.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/markitup/sets/bbcode/set.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/json2.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/jquery.uploadify/swfobject.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/jquery.uploadify/jquery.uploadify.v2.1.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/simple_tpl.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/upload_attachment.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lbforum/scripts/common.js"></script>
    <script type="text/javascript">
        mySettings['previewParserPath']='{% url markitup_preview %}';
	    $("#id_message").markItUp(mySettings);
        url_attachments_ajax_change_descn = "{% url attachments_ajax_change_descn %}";
        url_attachments_ajax_delete = "{% url attachments_ajax_delete %}";
        url_attachments_ajax_upload = "{% url attachments_ajax_upload %}";
		ify_uploader = '{{ STATIC_URL }}lbforum/scripts/jquery.uploadify/uploadify.swf';
		ify_script = '{% url attachments_uploadify %}';
		ify_cancelImg = '{{ STATIC_URL }}lbforum/styles/Oxygen/cancel.png';
		session_key = '{{ session_key }}';
        $(function() {
            {% for o in unpublished_attachments %}
            add_attachment({'id': '{{o.id}}','url': '{{o.file.url}}','fn': '{{o.org_filename}}','descn':'{{o.description}}'});
            {% endfor %}
            {% for o in post.attachments.all %}
            add_attachment({'id': '{{o.id}}','url': '{{o.file.url}}','fn': '{{o.org_filename}}','descn':'{{o.description}}'});
            {% endfor %}
        });
    </script>
    <script type="text/html" id="attachment_li_tmpl">
        <li id="attachment_<%=id%>" class="nb">
        <a class="filename" href="<%=url%>" target="_blank"><%=fn%></a>
        <span class="icon descn" style="">&nbsp;</span>
        <span style="display: none;">
        <input class="fld-descn" value="<%=descn%>"/>
        <a class="submit-descn" href="#">{% trans "submit" %}</a>
        </span>
        <span class="icon remove">&nbsp;</span>
        <span class="icon insert">&nbsp;</span>
        <span class="ext">&nbsp;</span>
        </li>
    </script>
{% endblock %}

lbforum/templates/lbforum/recent.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
  recent posts.
</body>
</html>